---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ehymet

<!-- badges: start -->
<!-- badges: end -->

The **ehymet** (Methodologies for functional data based on the epigraph and hypograph indexes) package define the epigraph, the hypograph and their modified versions for functional datasets in one and multiple dimensions. These indexes allow to transform a functional dataset into a multivariate one, where usual clustering techniques can be applied. This package implements EHyClus method for clustering functional data in one or multiple dimension.

## Related Papers:

- Belén Pulido, Alba M. Franco-Pereira, Rosa E. Lillo (2023).
  "A fast epigraph and hypograph-based approach for clustering functional data."
  _Statistics and Computing_, **33**, 36.
  doi: [10.1007/s11222-023-10213-7](https://doi.org/10.1007/s11222-023-10213-7)

- Belén Pulido, Alba M. Franco-Pereira, Rosa E. Lillo (2023).
  "The epigraph and the hypograph indexes as useful tools for clustering multivariate functional data."
  doi: [10.48550/arXiv.2307.16720](https://doi.org/10.48550/arXiv.2307.16720)

## Installation

You can install the development version of ehymet from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("bpulidob/ehymet")
```


